version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: project_sthenos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: flp1521
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: project_sthenos_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project_sthenos_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: flp1521
    depends_on:
      - db

volumes:
  postgres-data: