
CREATE TABLE IF NOT EXISTS category (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	measure varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "routine" (
	creation_date date NULL,
	enabled bool NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT routine_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS exercise (
	category int4 NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(255) NULL,
	difficulty varchar(255) NULL,
	image_url varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT exercise_pkey PRIMARY KEY (id),
	CONSTRAINT fk7vvqqdx24pa638ngixnwf2jrk FOREIGN KEY (category) REFERENCES public.category(id)
);

CREATE TABLE IF NOT EXISTS record (
	creation_date date NULL,
	exercise int4 NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	overload int4 NULL,
	quantity int4 NULL,
	CONSTRAINT record_pkey PRIMARY KEY (id),
	CONSTRAINT fksjvguwngf58vxc28otwcp0cns FOREIGN KEY (exercise) REFERENCES public.exercise(id)
);

CREATE TABLE IF NOT EXISTS routine_day (
	exercise int4 NULL,
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	repetitions int4 NULL,
	"routine" int4 NULL,
	series int4 NULL,
	"day" varchar(255) NULL,
	CONSTRAINT routine_day_pkey PRIMARY KEY (id),
	CONSTRAINT fkdv0x6ujb8611yie6iqtyp8t7k FOREIGN KEY ("routine") REFERENCES public."routine"(id),
	CONSTRAINT fkfq09xqqfa4omtm2dxvw02ota8 FOREIGN KEY (exercise) REFERENCES public.exercise(id)
);